### ISSUE TITLE
When will we be able do select minutes?

### ISSUE THREAD

**Issue by jr69** [ripjar/material-datetime-picker#103]
Hi, I am just wondering if we can select minutes with this

Maybe theres a branch or something I can pull?

**Comment by jwhitfieldseed** [comment]
Duplicate of #72

**Comment by jwhitfieldseed** [comment]
I this believe fork has a branch for minutes: https://github.com/Pako7/material-datetime-picker

I've asked @Pako7 to open a PR. If that doesn't get opened, I'll add the feature soon.
