### ISSUE TITLE
Does this work with react?

### ISSUE THREAD

**Issue by jr69** [ripjar/material-datetime-picker#104]
And if it does, how would one import it and use it as a component?

**Comment by lcc15** [comment]
It's vanilla js so you can import it as is or wrap it as a component.

I had troubles importing the npm version though. Webpack complains about missing tokens. So i used the 
.`js` file in `/dist`.

**Comment by jwhitfieldseed** [comment]
@lcc15 The `1.0.1` release has a couple of issues including the one you found. A `2.0.0` release which fixes imports for all bundlers is due soon - just waiting for the npm ownership to be transferred to me.

**Comment by jwhitfieldseed** [comment]
The standard way of using vanilla JS components in React is to define your own component that wraps this one. Briefly, something like this:

```
import React from 'react';
import MaterialDateTimePicker from 'material-datetime-picker';

class DatePicker extends React.Component {
  
  // this component makes its own DOM updates, so tell React not to make any changes
  shouldComponentUpdate() {
    return false;
  }

  componentWillReceiveProps(nextProps) {
    // use any values from `nextProps` to update the picker state, for example:
    this.picker.set(nextProps.newDate);
  }

  // the container element has been added to the DOM, so create the picker
  componentDidMount() {
    this.picker = new MaterialDateTimePicker({
      container: this.refs.container
    });
  }

  render() {
    // create the picker's wrapper component
    return <div ref={el => this.container = el}>;
  }
}
