### ISSUE TITLE
Close on ESC and when clicking outside of the modal

### ISSUE THREAD

**Issue by josdejong** [ripjar/material-datetime-picker#128]
I've just spend a couple of hours trying to get all sorts of date pickers working, and stumbled upon `material-datetime-picker` which is exactly what I needed! It looks great and is not tight to an `input` field (I want to open the date picker when clicking a button). Thanks!

A small suggestion: It would be nice if we could (optionally?) close the date picker when pressing the ESC key, and also when clicking outside of the date picker.

**Comment by CodeDG** [comment]
I need it.

**Comment by jwhitfieldseed** [comment]
Released in [v2.4.0](https://github.com/ripjar/material-datetime-picker/releases/tag/v2.4.0)

**Comment by josdejong** [comment]
This is good news, thanks Joe!

**Comment by jwhitfieldseed** [comment]
You are welcome, thanks for the appreciation 😄
