### ISSUE TITLE
material-datetime-picker for targetting an input element and invoking the picker using jquery or javascript?

### ISSUE THREAD

**Issue by Apurva1590** [ripjar/material-datetime-picker#132]
I want materialize datetime picker for an input form field like we have datepicker and timepicker separately available in jquery and javascript. 
For example: timepicker -  $('.timepicker').pickatime()
datepicker -  $('.datepicker').pickadate()

likewise,  I need for datetime picker, is this thing available ?

**Comment by Gorzas** [comment]
The library doesn't use jQuery and you really don't need it, but you can create your own wrapper for jQuery using the example code for inputs. :)

i.e. this may work:

```
jQuery.fn.datetimepicker = function (opts) {
  $(this).each(
    (i, input) => {
      const picker = new MaterialDatePicker(opts);
      
      input.addEventListener('focus', () => picker.open());
    }
  );
};
```
After that, you can do this:

```
$('.c-datepicker-input').datetimepicker()
```

You'll need also to handle submit event, like updating the current value of the input.
