### ISSUE TITLE
Change to minutes selection after an hour is selected

### ISSUE THREAD

**Issue by Gorzas** [ripjar/material-datetime-picker#133]
I've seen a kind of minor UX problem. The users don't know how to set minutes after they have selected an hour in the datetimepicker because the screen still shows the hours. So, as an UX improvement, we can show the minutes selection after they click an specific hour. What do you think?

I'm going to develop it and PR the improvement so you can see it.

**Comment by jwhitfieldseed** [comment]
I agree that would be an improvement. I look forward to seeing your PR 👍

**Comment by jwhitfieldseed** [comment]
Released in (v2.4.0)[https://github.com/ripjar/material-datetime-picker/releases/tag/v2.4.0]
