### ISSUE TITLE
Implement starting day and locale support

### ISSUE THREAD

**Issue by zuffik** [ripjar/material-datetime-picker#150]
I would like to have an option to set my own locale or at least day labels above the calendar.
Next it would be good to choose what day is the starting day of week (monday instead of sunday).
I have tried this:
```javascript
let mom = moment();
mom.locale(this.config.locale.short);
mom.isoWeekday(1);
mom.startOf('isoweek');
let picker = new MaterialDatetimePicker({
    'default': mom
});
```
The starting day stays untouched. 
Header is translated but day labels, *OK* and *Cancel* buttons are still in english.

Thanks

**Comment by schaermu** [comment]
The start of the week can be set as soon as #152 is merged. As for localization options, i'm not quite sure what rome provides, didn't find anything on a first glimpse (https://github.com/bevacqua/rome#romeelem-options)

**Comment by zuffik** [comment]
Thank you, I did not notice that merge. 

In rome package they recommended to set up localization with moment.js.
