### ISSUE TITLE
Use with input fields

### ISSUE THREAD

**Issue by p-Enzi** [ripjar/material-datetime-picker#43]
For a non jQuery-javascript professionell it is not obvious how to use the script as a real DatePicker with the inputfield set to a choosen date or time.
A demo with an input-field would be very appreciated from most users I guess.

**Comment by Jivings** [comment]
Will do, thanks for the feedback!

**Comment by amichel86** [comment]
That would be great, thank you! :)

**Comment by Jivings** [comment]
@amichel86 I've added better form input info to the README, and created an example codepen [here][0].

[0]: http://codepen.io/Jivings/pen/QEjbGw

**Comment by amichel86** [comment]
Holy macaroni, thank you!

I was wondering, is it possible to remove easily the time/calendar icons and have the "Monday Jan 2015 10th" panel on the left side of the calendar?

I am very comfortable with CSS but I want to achieve a certain design and I want to do it in a clean way. The last thing I would like to do is localize the calendar to French. Possible? :)

Thanks a lottttt!
