### ISSUE TITLE
How do you select minutes?

### ISSUE THREAD

**Issue by artknight** [ripjar/material-datetime-picker#72]

**Comment by leifdejong** [comment]
Same question

**Comment by kevindu1993** [comment]
Same question

**Comment by Jivings** [comment]
Currently you cannot select minutes. However, it should be relatively simple to implement.

**Comment by Pako7** [comment]
Hi Jivings.

I have added some code to allow to choose minutes.

Could I share that ?

**Comment by artknight** [comment]
please do!

**Comment by Jivings** [comment]
@Pako7 great! Open a PR :)

**Comment by artknight** [comment]
@Jivings  When will the PR be merged?

**Comment by jwhitfieldseed** [comment]
I'm resolving some issues with the build system. The PR will be merged shortly after that.

**Comment by CasperLaiTW** [comment]
Hi @jwhitfieldseed 

I follow material design time picker to making the choose minutes. (different with @Pako7 PR)

I have no idea which format is good for this. 

Should I open a PR for this?

![choose-minutes](https://cloud.githubusercontent.com/assets/5094008/22183106/13906ec4-e0f1-11e6-8d59-5c62319f6c8f.gif)

**Comment by jwhitfieldseed** [comment]
@CasperLaiTW looks great! please do open a PR.

**Comment by CasperLaiTW** [comment]
Hi @jwhitfieldseed 

Sure, I will open a PR, but I think we solve #107 first.

The issue also happened to selecting minutes.

**Comment by jwhitfieldseed** [comment]
Added in #119 by the awesome @CasperLaiTW!

Released as [https://github.com/ripjar/material-datetime-picker/releases/tag/v2.1.0](v2.1.0).
