### ISSUE TITLE
Issue with mozilla

### ISSUE THREAD

**Issue by muhunthanmano** [ripjar/material-datetime-picker#73]
The calendar icon and the time icons are not displaying in the mozila(version 46.0) in ubuntu
![topost](https://cloud.githubusercontent.com/assets/3600412/14912068/77f51d9a-0e17-11e6-8e65-4d0066fd1926.png)

**Comment by Jivings** [comment]
Interesting, can you check to see if the material fonts are being loaded? Can you still click the icons?

**Comment by muhunthanmano** [comment]
I checked with this (my machine is Ubuntu mozila -version 46.0 )   [](https://ripjar.github.io/material-datetime-picker/)  
The material fonts are loaded ,  the left and right arrow icon is showing

**Comment by Rambou** [comment]
Same problem here. Anyone fixed that yet?

**Comment by israel-viveros** [comment]
The problem is because is using pseudo-element(:after) in tag <input>

http://stackoverflow.com/questions/2587669/can-i-use-the-after-pseudo-element-on-an-input-field

**Comment by jwhitfieldseed** [comment]
Released in `2.0.3`
