### ISSUE TITLE
Not working with Meteor Apps using Materialize (36 errors)

### ISSUE THREAD

**Issue by mertyildiran** [ripjar/material-datetime-picker#88]
What I'm trying to achieve is adding a datetime picker input element to one of my forms in my [Meteor](https://www.meteor.com/) project that using [Materialize](http://materializecss.com/) as its CSS framework. My project's [GitHub repository](https://github.com/mertyildiran/Dermatron).

So I have found your `material-datetime-picker` [npm package](https://www.npmjs.com/package/material-datetime-picker) and its [GitHub repository](https://github.com/ripjar/material-datetime-picker).

The problem is when I follow the instructions on GitHub or npm page and add the necessary lines to my project I get a lot of (36) error messages on my [Developer Tools](https://developer.chrome.com/devtools) and I don't know why am I getting these errors and how to solve them:

First of all I installed the package with `meteor npm install --save material-datetime-picker` then;

**client/views/appointments/form_appointments:**

```
<div class="form-group">
    <label for="input_appointmentDatetime">appointmentDatetime</label>
    <input type="datetime-local" class="form-control"
        placeholder="Date"
        id="input_appointmentDatetime"
        value="{{appointmentDatetime}}">
</div>
```

**client/lib/extras.js :**

```
Template.form_appointments.onRendered(function () {

  import MaterialDateTimePicker from 'material-datetime-picker';

  const picker = new MaterialDateTimePicker()
      .on('submit', (val) => console.log(`data: ${val}`))
      .on('open', () => console.log('opened'))
      .on('close', () => console.log('closed'));

  document.querySelector('#input_appointmentDatetime')
      .on('click', () => picker.open());

});
```

**Developer Tools > Console > Errors:**

[![enter image description here](http://i.stack.imgur.com/yvAK4.png)](http://i.stack.imgur.com/yvAK4.png)

I also tried to use the standalone version of `material-datetime-picker` but this it ended up as a CSS mess and cannot even switch into timepicker page so it was also useless.

This time **client/lib/extras.js** was:

```
Template.form_appointments.onRendered(function () {

  const picker = new MaterialDatePicker({})
    .on('submit', (d) => {
      output.innerText = d;
    });

  const el = document.querySelector('#input_appointmentDatetime');
  el.addEventListener('click', () => {
    picker.open();
  }, false);

});
```

and result (there was not even a clock or calendar icon):

[![enter image description here](http://i.stack.imgur.com/VrsxG.png)](http://i.stack.imgur.com/VrsxG.png)

**Comment by Jivings** [comment]
Sorry, there are problems using importing the picker from node_modules and the fact that babel wont compile it. 

I need to fix this but currently have no time to dedicate to it. 

I suggest using the files that the demo is using (which can be found [here](https://github.com/ripjar/material-datetime-picker/tree/gh-pages/picker)). You will also need to include your own version of moment. I use the one from [here](https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js).
