### ISSUE TITLE
Language translation (locale)

### ISSUE THREAD

**Issue by lorenzodetomasi** [ripjar/material-datetime-picker#89]
Is it possible to set a different locale, i.e. fr or it?
I have a multi-language website, so I need to get the value of html lang attribute and set it as the value of an option that changes the date-time-picker language.
Can you send me a default locale settings file, so I can send you the Italian version (if you don't already have it).
Thank you.

**Comment by Jivings** [comment]
I haven't tested this, but `moment` (the time/date library used) supports localisation so you should be able to set the locale settings yourself if you run this code before including the picker js;

```js
moment.locale('fr', {
    months : "janvier_février_mars_avril_mai_juin_juillet_août_septembre_octobre_novembre_décembre".split("_"),
    monthsShort : "janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.".split("_"),
    weekdays : "dimanche_lundi_mardi_mercredi_jeudi_vendredi_samedi".split("_"),
    weekdaysShort : "dim._lun._mar._mer._jeu._ven._sam.".split("_"),
    weekdaysMin : "Di_Lu_Ma_Me_Je_Ve_Sa".split("_")
})
```

You can find the full details [here][0].

[0]: http://momentjs.com/docs/#/i18n/

**Comment by lorenzodetomasi** [comment]
I'm using it at http://www.villalariflorence.com/it/homepage/, with `<script type='text/javascript' src='http://www.villalariflorence.com/wp-content/themes/villalari/ripjar-material-datetime-picker/js/datepicker.standalone.js?ver=20161021'></script>` in the footer.
Where have I to add the code you have suggested?
Thank you.

**Comment by Jivings** [comment]
@lorenzodetomasi anywhere before that script tag.

**Comment by lorenzodetomasi** [comment]
Before loading datepicker.standalone.js?
Have I to load other scripts before or after?

**Comment by lorenzodetomasi** [comment]
I cannot solve this problem.
Look at http://www.villalariflorence.com/fr/page-daccueil/
The error "locale.js?ver=4.6.1:2 Uncaught ReferenceError: moment is not defined" persists.

Thank you in advance.

**Comment by jwhitfieldseed** [comment]
Hi, can you check out the [new example](https://github.com/ripjar/material-datetime-picker/blob/master/demo/index.html#L69):

You can load the datepicker from script tags with a specific locale:

```
<script src="https://unpkg.com/babel-polyfill@6.2.0/dist/polyfill.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.js"></script>

<!-- moment locale script -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/locale/it.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/rome/2.1.22/rome.standalone.js"></script>
<script src="../dist/material-datetime-picker.js" charset="utf-8"></script>
```
