### ISSUE TITLE
Need Help for integration inside an Aurelia project using Aurelia-CLI

### ISSUE THREAD

**Issue by Ganbin** [ripjar/material-datetime-picker#90]
Hello,

I like your library and it use ES6 which is nice to use in my Aurelia project. However, I cannot make it to work inside my project.
I include the `node_modules/material-datetime-picker/dist/js/datepicker.js` in my bundle, but when I try to create a new instance of the dateTimePicker like in your doc : 

`const picker = new MaterialDateTimePicker();`

I get this error : `TypeError: _materialDatetimePicker2.default is not a constructor`

My project use Babel as transpiler and use the `es2015-loose` plugin.

Could you help me to integrate this module inside my project? What could be the cause of this problem?

I think that my bundle is correct because I don't get any error when I'm bundling my files. But the error occurs not on the import, but when I use the `new MaterialDateTimePicker()` constructor.

**Comment by Jivings** [comment]
Sorry, there are problems using importing the picker from node_modules and the fact that babel wont compile it.

I need to fix this but currently have no time to dedicate to it.

I suggest using the files that the demo is using (which can be found [here][1]). You will also need to include your own version of moment. I use the one from [here][2].

[1]: https://github.com/ripjar/material-datetime-picker/tree/gh-pages/picker
[2]: https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js

**Comment by Ganbin** [comment]
Ok thanks I will take a look when I will want to integrate this feature in my formular.

**Comment by Ganbin** [comment]
I keep it open for the day I can integrate in my project well.

**Comment by Thanood** [comment]
From the looks of `datepicker.js`, it isn't an AMD file but a CommonJS file build with browserify. Aurelia CLI expects AMD type modules, because it's using requirejs internally. So this won't work, unfortunately. 

Maybe it could be solved by also transpiling the `material-datetime-picker` source directly to AMD but I've tried that and failed. Anyway, leaving this here as an idea. :)

**Comment by jwhitfieldseed** [comment]
Hi, thanks for your patience. The old build process had a few problems, which I have resolved. I'll cut a `2.0.0` release in the next few days.

The `main`entry point file is a UMD file, so it works with CommonJS and AMD (and as a `<script>` tag). 

There is also a `module`/`jsnext:main` entry point for tools like rollup that support ES2015 modules directly.

**Comment by jwhitfieldseed** [comment]
@Ganbin @Thanood can you try depending on `2.0.0-pre`? 

The build issues should be resolved there.

**Comment by Thanood** [comment]
@jwhitfieldseed @Ganbin 
Worls for me! 👍

**Comment by jwhitfieldseed** [comment]
Released as `2.0.0`. Thanks for checking!
