### ISSUE TITLE
Passing a configurations object throws an error

### ISSUE THREAD

**Issue by showcasefloyd** [ripjar/material-datetime-picker#93]
I'm trying to integrate this library into a an MDL project I'm building but the configuration doesn't seem to work.

```
 enableCal: function(__feild){
        var $element = $(__feild);

        var picker = new MaterialDatePicker({
            el: $element,
            openedBy: 'onclick'
        });

       $element.on('focus', function(){
            picker.open();
        });

}

```

When I run this in the browser I get:

```
index.js:207 Uncaught TypeError: this.options.el.setAttribute is not a function
    at DateTimePicker.set
```

Any ideas?

**Comment by showcasefloyd** [comment]
Okay, i've tried a different approach and I'm not getting any errors, but not it doesn't fire any more.

```
            var picker = new MaterialDatePicker({
                el: $element,
                openedBy: 'focus',
                container: document.body,   
            }).on('submit', function (val) {
                $element.val(val.format("DD/MM/YY"));
            });
```

**Comment by jwhitfieldseed** [comment]
Hi, thanks for the issue. It looks like you're using a jQuery selection for `el`. It should be a vanilla DOM Element.

For example,

```js
var picker = new MaterialDatePicker({
  el: $element[0]
});
```

**Comment by showcasefloyd** [comment]
Okay, thanks for letting me know. Perhaps you want to update your documentation to reflect this.

I appreciate the feedback.

**Comment by jwhitfieldseed** [comment]
The docs don't mention jQuery, and the docs have an example with `document.querySelector`. How could I update them to make that clearer?

**Comment by jwhitfieldseed** [comment]
I added a note, hopefully that will help.

**Comment by showcasefloyd** [comment]
Thanks so much
