### ISSUE TITLE
How do I get openedBy to work?

### ISSUE THREAD

**Issue by showcasefloyd** [ripjar/material-datetime-picker#94]
```
     var picker = new MaterialDatePicker({
                el: '#Modified',
                openedBy: 'focus'
            }).on('submit', function (val) {
                console.log(val)
            });
```

**Comment by jwhitfieldseed** [comment]
Hi, thanks for the issue. I'm sorry about this - it looks like a feature that was never actually implemented. I'm not sure why it was documented. I'll remove it from the docs.

**Comment by randoum** [comment]
It's still in the docs FYI
https://ripjar.github.io/material-datetime-picker/
