### ISSUE TITLE
Cannot find module 'material-datetime-picker' With Angular 2 CLI

### ISSUE THREAD

**Issue by janiukjf** [ripjar/material-datetime-picker#96]
Hey. So I installed using npm install material-datetime-picker --save. I added the import statement at the top of my directive file, and when I went to build the project, it throws the error in the title. Angular CLI uses webpack, and the full stack trace in the build looks like this:

`ERROR in ./src/app/datetimepicker.directive.ts
Module build failed: Error: /Users/jessicajaniuk/repos/JessicaJaniuk/src/app/datetimepicker.directive.ts (2,36): Cannot find module 'material-datetime-picker'.)
    at _checkDiagnostics (/Users/jessicajaniuk/repos/JessicaJaniuk/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /Users/jessicajaniuk/repos/JessicaJaniuk/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./src/app/app.module.ts 27:0-69
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main`

I've just been striking out with date time pickers with material design and angular 2. I was so hoping this would work. Any help would be appreciated.

**Comment by jwhitfieldseed** [comment]
Hi, thanks for the issue.

This seems to be a problem with module resolution in TypeScript, which I don't know much about. If I create two files at the root of an NG2 project:

```js
// test-require.js
const MaterialDatetimePicker = require("material-datetime-picker");
console.log(MaterialDatetimePicker);
```

```js
// test-import.ts
import MaterialDatetimePicker from "material-datetime-picker";
console.log(MaterialDatetimePicker);
```

And run both with `./node_modules/.bin/ts-node`, `test-import.ts` throws with the error that you found. `test-require.ts` is fine.

Do you know what we would need to change to make for the module `import`-able in TypeScript?

**Comment by jwhitfieldseed** [comment]
You need to make TypeScript aware of `material-datetime-picker`. Create the file `src/typings.d.ts` with contents:

```
declare module 'material-datetime-picker';
```

From the [Angular CLI docs](https://github.com/angular/angular-cli#3rd-party-library-installation)
